name: Release

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run Test
        run: |
          deno test
      - name: Set Tag and Compile
        run: |
          echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          deno compile --allow-read --v8-flags=--max-old-space-size=8192 --target x86_64-unknown-linux-gnu --output base85-linux-x86 cli.ts
          deno compile --allow-read --v8-flags=--max-old-space-size=8192 --target x86_64-pc-windows-msvc --output base85-windows-x86 cli.ts
          deno compile --allow-read --v8-flags=--max-old-space-size=8192 --target x86_64-apple-darwin --output base85-macos-x86 cli.ts
          deno compile --allow-read --v8-flags=--max-old-space-size=8192 --target aarch64-apple-darwin --output base85-macos-arm cli.ts
      - name: Get commit summary
        id: get_commit_summary
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
          COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
          echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: |
            ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}
          draft: false
          prerelease: false
      - name: Upload Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "base85-*"